config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registration], controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i(index show destroy)

  # ログアウト用
  # devise_scope :users do
  #   delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  root 'top_pages#top'
  resources :parts_lists, only: %i(index)
  resources :products
  resources :markets, only: %i(index edit update)
end

app/models/market.rb
class Market < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :code, presence: true, length: { maximum: 500 }
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

  def index
    @markets = Market.all
  end

  def edit
    @market = Market.find(params[:id])
  end

  def update
    @market = Market.find(params[:id])
    if @market.update_attributes(market_params)
      flash[:notice] = "#{@market.name}を編集しました。"
      redirect_to markets_url
    else
      flash[:alert] = @market.errors.full_messages.join("<br>").html_safe
      render :edit
    end
  end

  private
  
    def market_params
      params.require(:market).permit(:name, :code)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_with(model: @market, local: true) do |f| %>
  <%= f.label :name, class: "label-new" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :code, class: "label-new" %>
  <%= f.text_field :code, class: "form-control" %>

  <%= f.submit "#{yield(:button_text)}", class: "btn btn-secondary btn-block btn-new"  %>
<% end %>

app/views/markets/edit.html.erb
<% provide(:title, '編集') %>
<% provide(:button_text, '編集') %>

<h3>編集</h3>

<div class="container container-top">
  <div class="col col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/markets/index.html.erb
<table class="table table-responsive table-hover">
  <% @markets.each do |market| %>
    <thead>
      <tr>
        <th></th>
        <th><%= Market.human_attribute_name :name %></th>
        <th><%= Market.human_attribute_name :code %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to "", edit_market_path(market), class: "fas fa-edit" %></td>
        <td><%= market.name %></td>
        <td><%= market.code %></td>
      </tr>
    </tbody>
  <% end %>
</table>