config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registration], controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i(index show destroy)

  # ログアウト用
  # devise_scope :users do
  #   delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  root 'top_pages#top'
  resources :parts_lists, only: %i(index)
  resources :products
  resources :markets, only: %i(index edit update)
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market.rb
class Market < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :code, presence: true, length: { maximum: 500 }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :serial, length: { maximum: 100 }
  validates :url, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable,
         :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]

  # devise :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

      user.skip_confirmation_notification!
      user.skip_confirmation!
    end
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user! # 追記 (userの部分はmodel名)

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    parts_lists_path
  end 
  
  #ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

  def index
    @markets = Market.all
  end

  def edit
    @market = Market.find(params[:id])
  end

  def update
    @market = Market.find(params[:id])
    if @market.update_attributes(market_params)
      flash[:notice] = "#{@market.name}を編集しました。"
      redirect_to markets_url
    else
      flash[:alert] = @market.errors.full_messages.join("<br>").html_safe
      render :edit
    end
  end

  private
  
    def market_params
      params.require(:market).permit(:name, :code)
    end
end

app/controllers/parts_lists_controller.rb
class PartsListsController < ApplicationController
  before_action :user_and_admin_signed_in?
  
  def index
    @products = Product.all
    if params[:name].present?
      @products = Product.where('name LIKE ?', "%#{params[:name]}%")
    else
      @products = Product.all.page(params[:page])
    end
  end
end

private

  def user_and_admin_signed_in?
    unless user_signed_in? || admin_signed_in?
      redirect_to new_user_session_path
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i(edit update destroy)
  before_action :authenticate_admin!

  def index
    @products = Product.all
    if params[:name].present?
      @products = Product.where('name LIKE ?', "%#{params[:name]}%")
    else
      @products = Product.all.page(params[:page])
    end
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "#{@product.name}を登録しました。"
      redirect_to products_url
    else
      flash[:alert] = @product.errors.full_messages.join("<br>").html_safe
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update_attributes(product_params)
      flash[:notice] = "#{@product.name}を編集しました。"
      redirect_to products_url
    else
      flash[:alert] = @product.errors.full_messages.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:alert] = "#{@product.name}を削除しました。"
    redirect_to products_url
  end

  private

    def product_params
      params.require(:product).permit(:name, :serial, :url)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  before_action :authenticate_user! # 追記 (userの部分はmodel名)

  def top
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, only: %i(index destroy) # 追記 (userの部分はmodel名)
  before_action :authenticate_user!, only: %i(show)

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:alert] = "#{@user.email}を削除しました。"
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_name = "")
    base_title = "yamato"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end

  def header_logo_link
    if user_signed_in?
      parts_lists_path
    elsif admin_signed_in?
      parts_lists_path
    else
      new_user_session_path
    end
  end

  def search_name
    params[:name].present?
  end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/parts_lists_helper.rb
module PartsListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def provider
    p = current_user.provider
    p == "google_oauth2" ? p = "google" : p
  end
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-right">
  <div class="container">
    <%= link_to "Husq Parts", header_logo_link, id: "logo" %>

    <% if user_signed_in? %>
      <nav class="nav navbar-nav navbar-right">
        <ul class="pc-display">
          <li><%= link_to current_user.email, user_path(current_user) %></li>
          <li><%= link_to "パーツ表", parts_lists_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
        <ul class="mobile-display">
          <li><%= link_to "", user_path(current_user), class: "fas fa-user-circle" %></li>
          <li><%= link_to "", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt" %></li>
        </ul>
      </nav>
    <% end %>

    <% if admin_signed_in? %>
      <nav class="nav navbar-nav navbar-right">
        <ul class="pc-display">
          <li><%= link_to "パーツ表", parts_lists_path %></li>
          <li><%= link_to "編集", products_path %></li>
          <li><%= link_to "登録者一覧", users_path %></li>
          <li><%= link_to "管理者情報", '#' %></li>
          <li><%= link_to "Market情報", markets_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
        <ul class="mobile-display">
          <li><%= link_to "", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt" %></li>
        </ul>
      </nav>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  full_title(yield(:title))  %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name=”viewport” content=”width=device-width, initial-scale=1”>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0"> <!-- レスポンシブ -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
    
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' unless request.path.include?("admins/sign_in") %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>
    </div>
    
    <% if Rails.env.development? %>
      <div class="container">
        <%= debug(params) %>
      </div>
    <% end %>
  </body>
</html>