config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registration], controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i(index show destroy)

  # ログアウト用
  # devise_scope :users do
  #   delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  root 'top_pages#top'
  resources :parts_lists, only: %i(index)
  resources :products
  resources :markets, only: %i(index edit update)
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :serial, length: { maximum: 100 }
  validates :url, presence: true, length: { maximum: 1000 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i(edit update destroy)
  before_action :authenticate_admin!

  def index
    @products = Product.all
    if params[:name].present?
      @products = Product.where('name LIKE ?', "%#{params[:name]}%")
    else
      @products = Product.all.page(params[:page])
    end
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "#{@product.name}を登録しました。"
      redirect_to products_url
    else
      flash[:alert] = @product.errors.full_messages.join("<br>").html_safe
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update_attributes(product_params)
      flash[:notice] = "#{@product.name}を編集しました。"
      redirect_to products_url
    else
      flash[:alert] = @product.errors.full_messages.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:alert] = "#{@product.name}を削除しました。"
    redirect_to products_url
  end

  private

    def product_params
      params.require(:product).permit(:name, :serial, :url)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |f| %>
  <%= f.label :name, class: "label-new" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :serial, class: "label-new" %>
  <%= f.text_field :serial, class: "form-control" %>

  <%= f.label :url, class: "label-new" %>
  <%= f.text_area :url, class: "form-control", rows: 3 %>

  <%= f.submit "#{yield(:button_text)}", class: "btn btn-secondary btn-block btn-new"  %>
<% end %>

app/views/products/edit.html.erb
<% provide(:title, '編集') %>
<% provide(:button_text, '編集') %>

<h3>編集</h3>

<div class="container container-top">
  <div class="col col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<%= form_with url: products_path, method: :get, local: true do |f| %>
  <div class="col col-md-4 search-form"">
    <div class="input-group input-group">
      <%= f.text_field :name, class: "form-control" %>
      <div class="input-group-btn">
        <%= f.submit "検索", class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
<% end %>

<div class="col col-md-8 paginate-parts-list">
  <%= paginate @products unless search_name %>
</div>


<div class="col col-md-12">
  <div class="btn-product-new">
    <!-- 登録 -->
    <%= link_to "", new_product_path, class: "fas fa-plus-circle fa-lg" %>
  </div>
</div>

<table class="table table-responsive table-hover">
  <% unless @products.blank? %>
    <thead>
      <tr>
        <th width="200"><%= Product.human_attribute_name :name %></th>
        <th></th>
        <th width="250"><%= Product.human_attribute_name :serial %></th>
        <th><%= Product.human_attribute_name :url %></th>
        <th></th>
      </tr>
    </thead>
  <% else %>
    <tbody>
      <tr>
        <td class="search-none-message"><%= link_to "登録型式がありません。", products_path, class: "fa-lg" %><%= link_to "", parts_lists_path, class: "fas fa-backspace fa-lg" %></td>
      </tr>
    </tbody>
  <% end %>
  
  <% @products.each do |product| %>
    <tbody>
      <tr>
        <td><%= product.name %></td>
        <td>
          <!-- 編集 -->
          <%= link_to "", edit_product_path(product), class: "fas fa-edit fa-lg" %>
        </td>
        <td><%= product.serial %></td>
        <td><%= product.url %></td>
        <td>
          <!-- 削除 -->
          <%= link_to "", product_path(product),
                              method: :delete,
                              data: { confirm: "#{product.name}のデータを削除します。"},
                              class: "fas fa-times-circle fa-lg" %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/products/new.html.erb
<% provide(:title, '登録') %>
<% provide(:button_text, '新規登録') %>

<div class="container container-top">
  <div class="col col-md-6 col-md-offset-3">
    <h3>パーツ表登録</h3>
    <%= render 'form' %>
  </div>
</div>